basePath: /
definitions:
  domain.Article:
    properties:
      author_id:
        type: integer
      content:
        minLength: 20
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        minLength: 10
        type: string
    required:
    - content
    - title
    type: object
  domain.Author:
    properties:
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
    type: object
  domain.SignInInput:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  domain.SignUpInput:
    properties:
      email:
        type: string
      name:
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  domain.UpdateArticleInput:
    properties:
      content:
        minLength: 20
        type: string
      title:
        minLength: 10
        type: string
    required:
    - content
    - title
    type: object
  domain.UpdateAuthorInput:
    properties:
      name:
        type: string
      surname:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Sample Server for News App
  title: News API
  version: "1.0"
paths:
  /articles:
    get:
      consumes:
      - application/json
      operationId: get-all-articles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Article'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get All Articles
      tags:
      - Articles
    post:
      consumes:
      - application/json
      operationId: create-articles
      parameters:
      - description: Article input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Create Article
      tags:
      - Articles
  /articles/{id}:
    delete:
      consumes:
      - application/json
      operationId: delete-article
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Delete Article
      tags:
      - Articles
    get:
      consumes:
      - application/json
      operationId: get-article-by-id
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Article'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get Article By Id
      tags:
      - Articles
    put:
      consumes:
      - application/json
      operationId: update-article
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Article input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateArticleInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Update Article
      tags:
      - Articles
  /articles/{id}/bookmark:
    get:
      consumes:
      - application/json
      operationId: add-article-in-bookmarks
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Add Article in bookmarks
      tags:
      - Articles
  /auth/home/bookmarks:
    get:
      consumes:
      - application/json
      operationId: get-bookmarks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Article'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get Bookmarks
      tags:
      - Users auth
  /auth/refresh:
    get:
      consumes:
      - application/json
      operationId: refresh
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Refresh
      tags:
      - Users auth
  /auth/sign-in:
    post:
      consumes:
      - application/json
      operationId: sign-in
      parameters:
      - description: Sign in input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Sign In
      tags:
      - Users auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      operationId: sign-up
      parameters:
      - description: Sign up input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Sign Up
      tags:
      - Users auth
  /authors:
    get:
      consumes:
      - application/json
      operationId: get-all-authors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Author'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get All Authors
      tags:
      - Authors
    post:
      consumes:
      - application/json
      operationId: create-author
      parameters:
      - description: Author input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Author'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Create Author
      tags:
      - Authors
  /authors/{id}:
    delete:
      consumes:
      - application/json
      operationId: delete-author
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Delete Author
      tags:
      - Authors
    get:
      consumes:
      - application/json
      operationId: get-author-by-id
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Author'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get Author By Id
      tags:
      - Authors
    put:
      consumes:
      - application/json
      operationId: update-author
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Author input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateAuthorInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Update Author
      tags:
      - Authors
  /authors/{id}/articles:
    get:
      consumes:
      - application/json
      operationId: get-author-articles
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/domain.Article'
              type: array
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Get Author Articles
      tags:
      - Authors
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
